#!/usr/bin/with-contenv bash
echo "Starting Terraria Server."

CMD="/app/TerrariaServer -x64 -config /config/serverconfig.txt -banlist /config/banlist.txt"
# Pass in world if set
if [ "${WORLD:-null}" != null ]; then
    if [ ! -f "/config/${world}" ]; then
        CMD="${CMD} -world /config/${WORLD} -autocreate 1 -worldname $(echo "${WORLD}" | cut -f 1 -d '.')"
    else
        CMD="${CMD} -world /config/${WORLD}"
    fi
fi

exec s6-setuidgid abc screen -DmS terraria ${CMD}