#!/usr/bin/with-contenv bash

# Setup user/group ids
if [ ! -z "${PUID}" ]; then
  if [ ! "$(id -u abc)" -eq "${PUID}" ]; then
    
    # usermod likes to chown the home directory, so create a new one and use that
    # However, if the new UID is 0, we can't set the home dir back because the
    # UID of 0 is already in use (executing this script).
    if [ ! "${PUID}" -eq 0 ]; then
      mkdir /tmp/temphome
      usermod -d /tmp/temphome abc
    fi
    
    # Change the UID
    usermod -o -u "${PUID}" abc
    
    # Cleanup the temp home dir
    if [ ! "${PUID}" -eq 0 ]; then
      usermod -d ${HOME} abc
      rm -Rf /tmp/temphome
    fi
  fi
fi

if [ ! -z "${PGID}" ]; then
  if [ ! "$(id -g abc)" -eq "${PGID}" ]; then
    groupmod -o -g "${PGID}" abc
  fi
fi